#!/bin/bash
clear
clear
cc consumer.c -o x
cc producer.c -o y
cc shutdown.c -o z
sleep 0.5

./x  10  10 26 5&
sleep 0.5 # allow the consumer to be ready
./y  5  10&
./y  2  25&
./y 10  23&
./y 14  28&
./y 20  17&
./y  2  1&
./y  1  4&
sleep 2
./y  2  11&
#./y  14  2&
#sleep 1
#./y  8  5&

sleep 50 # time you want to run the simulation before ending
./z


# ***************README****************************
#  Each new process is now shown before in the "new" state for 1 second before being put into the "ready" or "suspended" state.
#  Each terminated process is shown for 1 second with its time as 0, before it is removed from pcb and RAM.
# 
